// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 24/04/2025, 16:56:28
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["D:/codes/00-Personal/kartChampMaker/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/codes/00-Personal/kartChampMaker/frontend/src/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/codes/00-Personal/kartChampMaker/frontend/src/sections/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/codes/00-Personal/kartChampMaker/frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/codes/00-Personal/kartChampMaker/frontend/plugins/**/*.{js,ts,mjs}","D:/codes/00-Personal/kartChampMaker/frontend/composables/**/*.{js,ts,mjs}","D:/codes/00-Personal/kartChampMaker/frontend/utils/**/*.{js,ts,mjs}","D:/codes/00-Personal/kartChampMaker/frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","D:/codes/00-Personal/kartChampMaker/frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","D:/codes/00-Personal/kartChampMaker/frontend/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;